// Mocks generated by Mockito 5.4.6 from annotations
// in sample_book_app/test/presentation/app_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sample_book_app/domain/entities/book_entity.dart' as _i3;
import 'package:sample_book_app/domain/entities/book_response_entity.dart'
    as _i2;
import 'package:sample_book_app/domain/repositories/book_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBookResponseEntity_0 extends _i1.SmartFake
    implements _i2.BookResponseEntity {
  _FakeBookResponseEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBookEntity_1 extends _i1.SmartFake implements _i3.BookEntity {
  _FakeBookEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepository extends _i1.Mock implements _i4.BookRepository {
  @override
  _i5.Future<_i2.BookResponseEntity> fetchBooks({
    int? page = 1,
    String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBooks, [], {#page: page, #search: search}),
            returnValue: _i5.Future<_i2.BookResponseEntity>.value(
              _FakeBookResponseEntity_0(
                this,
                Invocation.method(#fetchBooks, [], {
                  #page: page,
                  #search: search,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.BookResponseEntity>.value(
              _FakeBookResponseEntity_0(
                this,
                Invocation.method(#fetchBooks, [], {
                  #page: page,
                  #search: search,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BookResponseEntity>);

  @override
  _i5.Future<_i3.BookEntity> fetchBookDetail(int? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBookDetail, [bookId]),
            returnValue: _i5.Future<_i3.BookEntity>.value(
              _FakeBookEntity_1(
                this,
                Invocation.method(#fetchBookDetail, [bookId]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.BookEntity>.value(
              _FakeBookEntity_1(
                this,
                Invocation.method(#fetchBookDetail, [bookId]),
              ),
            ),
          )
          as _i5.Future<_i3.BookEntity>);

  @override
  _i5.Future<_i2.BookResponseEntity> fetchBooksByTopic({
    required String? topic,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBooksByTopic, [], {
              #topic: topic,
              #page: page,
            }),
            returnValue: _i5.Future<_i2.BookResponseEntity>.value(
              _FakeBookResponseEntity_0(
                this,
                Invocation.method(#fetchBooksByTopic, [], {
                  #topic: topic,
                  #page: page,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.BookResponseEntity>.value(
              _FakeBookResponseEntity_0(
                this,
                Invocation.method(#fetchBooksByTopic, [], {
                  #topic: topic,
                  #page: page,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BookResponseEntity>);
}
